### ISSUE TITLE
Generated compilers require C# 9.0 to be build after upgrading from 4.1.0 to 4.2.2

### ISSUE THREAD

**Issue by Eshva** [jamescourtney/FlatSharp#93]
Namaste!
Today I've upgraded FlatSharp from 4.1.0 to 4.2.2 and got a problem during solution building with a few such error messages:
```
CaseCreated.fbs.generated.cs(106,56,106,64): error CS8400: Feature 'not pattern' is not available in C# 8.0. Please use language version 9.0 or greater.
```
It turns out compilers code contains such strings:
```csharp
if (index1Value is not null)
{
  runningSum += GetMaxSizeOf_c96a83b5ae264b13b4665aede73aac9f(index1Value);
}
```
Notice `is not null`. Seams like it's a feature of C# 9.0 which is not supported in .NET Core 3.1. I don't plan to move to .NET 5 for the moment. Can you return back old good `!= null`? Or I can return it back just tell me which files to start to look for this code?

**Comment by jamescourtney** [comment]
Sorry for accidentally including a breaking change in a minor revision. This one honestly didn't occur to me. I'll get 4.2.3 published later tonight with this fix.

However -- you *should* be able to use ```<LangVersion>9.0</LangVersion>``` with netcoreapp3.1, there will just be some 9.0-specific features that don't work, such as records, init-only properties, etc. FlatSharp compiles globally with 9.0 and I'm able to target net47 through net5.0. 

More broadly, this change is because I'm trying to start supporting some newer language features like init-only properties and nullable annotations.

**Comment by jamescourtney** [comment]
#94

**Comment by jamescourtney** [comment]
Version 4.2.3 will be available on Nuget shortly. Thanks again for bringing this to my attention so promptly.

For the record -- while I'm not completely decided, I think there is a pretty good chance that 4.2.3 will be the last version on C# 8. The next version of FlatSharp will likely be 5.0 + C# 9 (which will still work on older runtimes if you set the compiler directive to set language version to 9).

**Comment by Eshva** [comment]
Thank you James! I will test it today.
About .NET 5. From the point of view an enterprise developer, it's not the best situation. I don't tell about my case because I have a right to use almost what ever I want. But if we talk about a general enterprise developer, they can't use .NET 5 in production code because .NET 5 isn't an LTS version. I guess a solution can be a release branch for version 4.x where developers can contribute some bug fixes. But anyway it's up to you, you have no any obligations in this regard.

**Comment by Eshva** [comment]
Thank you. The version 4.2.3 works as expected well.
